In [14]:
import pandas as pd
event_coref = pd.read_csv('ali-baba-and-forty-thieves.verb_subj_dobj.srl.csv')
event_coref

,sentence_id,verb_id,verb,verb_start_byte,verb_end_byte,verb_start_byte_text,verb_end_byte_text,subj_coref_ids,subj_start_byte,subj_end_byte,subj_start_byte_text,subj_end_byte_text,dobj_coref_ids,dobj_start_byte,dobj_end_byte,dobj_start_byte_text,dobj_end_byte_text,event_label
0,1,0,are,38,41,95,98,"1,7,2",0.0,37.0,57.0,94.0,8,42.0,64.0,99.0,121.0,0
1,2,0,marries,51,58,174,181,2,33.0,50.0,156.0,173.0,11,59.0,74.0,182.0,197.0,1
2,2,1,becomes,79,86,202,209,2,33.0,50.0,156.0,173.0,NaN,87.0,97.0,210.0,220.0,1
3,2,2,building,99,107,222,230,2,33.0,50.0,156.0,173.0,10,108.0,134.0,231.0,257.0,1
4,2,3,marries,150,157,273,280,1,141.0,149.0,264.0,272.0,13,158.0,170.0,281.0,293.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,37,2,tried,74,79,4571,4576,55,64.0,73.0,4561.0,4570.0,1,80.0,91.0,4577.0,4588.0,1
108,37,3,kill,83,87,4580,4584,55,64.0,73.0,4561.0,4570.0,1,88.0,91.0,4585.0,4588.0,1
109,37,4,gives,96,101,4593,4598,1,93.0,95.0,4590.0,4592.0,4,102.0,110.0,4599.0,4607.0,1
110,37,5,marries,127,134,4624,4631,1,93.0,95.0,4590.0,4592.0,NaN,135.0,138.0,4632.0,4635.0,1
111,38,1,left,17,21,4665,4669,1,0.0,8.0,4648.0,4656.0,NaN,22.0,105.0,4670.0,4753.0,1

In [15]:
event_coref.iloc[2]['dobj_coref_ids']

nan

In [19]:
event_coref.loc[event_coref['subj_coref_ids'].isnull()==False]

,sentence_id,verb_id,verb,verb_start_byte,verb_end_byte,verb_start_byte_text,verb_end_byte_text,subj_coref_ids,subj_start_byte,subj_end_byte,subj_start_byte_text,subj_end_byte_text,dobj_coref_ids,dobj_start_byte,dobj_end_byte,dobj_start_byte_text,dobj_end_byte_text,event_label
0,1,0,are,38,41,95,98,"1,7,2",0.0,37.0,57.0,94.0,8,42.0,64.0,99.0,121.0,0
1,2,0,marries,51,58,174,181,2,33.0,50.0,156.0,173.0,11,59.0,74.0,182.0,197.0,1
2,2,1,becomes,79,86,202,209,2,33.0,50.0,156.0,173.0,NaN,87.0,97.0,210.0,220.0,1
3,2,2,building,99,107,222,230,2,33.0,50.0,156.0,173.0,10,108.0,134.0,231.0,257.0,1
4,2,3,marries,150,157,273,280,1,141.0,149.0,264.0,272.0,13,158.0,170.0,281.0,293.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,37,2,tried,74,79,4571,4576,55,64.0,73.0,4561.0,4570.0,1,80.0,91.0,4577.0,4588.0,1
108,37,3,kill,83,87,4580,4584,55,64.0,73.0,4561.0,4570.0,1,88.0,91.0,4585.0,4588.0,1
109,37,4,gives,96,101,4593,4598,1,93.0,95.0,4590.0,4592.0,4,102.0,110.0,4599.0,4607.0,1
110,37,5,marries,127,134,4624,4631,1,93.0,95.0,4590.0,4592.0,NaN,135.0,138.0,4632.0,4635.0,1
111,38,1,left,17,21,4665,4669,1,0.0,8.0,4648.0,4656.0,NaN,22.0,105.0,4670.0,4753.0,1

In [7]:
event_coref.iloc[:30]

,sentence_id,verb_id,verb,verb_start_byte,verb_end_byte,verb_start_byte_text,verb_end_byte_text,subj_coref_ids,subj_start_byte,subj_end_byte,subj_start_byte_text,subj_end_byte_text,dobj_coref_ids,dobj_start_byte,dobj_end_byte,dobj_start_byte_text,dobj_end_byte_text
0,1,0,are,38,41,95,98,"1,7,2",0.0,37.0,57.0,94.0,8,42.0,64.0,99.0,121.0
1,2,0,marries,51,58,174,181,2,33.0,50.0,156.0,173.0,11,59.0,74.0,182.0,197.0
2,2,1,becomes,79,86,202,209,2,33.0,50.0,156.0,173.0,NaN,87.0,97.0,210.0,220.0
3,2,2,building,99,107,222,230,2,33.0,50.0,156.0,173.0,10,108.0,134.0,231.0,257.0
4,2,3,marries,150,157,273,280,1,141.0,149.0,264.0,272.0,13,158.0,170.0,281.0,293.0
5,2,4,settles,175,182,298,305,1,141.0,149.0,264.0,272.0,NaN,NaN,NaN,NaN,NaN
6,3,0,is,17,19,355,357,1,0.0,16.0,338.0,354.0,NaN,20.0,73.0,358.0,411.0
7,3,1,collecting,28,38,366,376,1,8.0,16.0,346.0,354.0,NaN,51.0,59.0,389.0,397.0
8,3,3,happens,82,89,420,427,NaN,NaN,NaN,NaN,NaN,16,90.0,156.0,428.0,494.0
9,3,4,overhear,93,101,431,439,1,79.0,81.0,417.0,419.0,16,102.0,156.0,440.0,494.0
10,5,0,opens,3,8,565,570,NaN,0.0,2.0,562.0,564.0,3,9.0,83.0,571.0,645.0
11,5,1,seals,42,47,604,609,NaN,0.0,2.0,562.0,564.0,3,48.0,54.0,610.0,616.0
12,6,1,gone,21,25,668,672,20,5.0,16.0,652.0,663.0,NaN,NaN,NaN,NaN,NaN
13,6,2,enters,36,42,683,689,1,27.0,35.0,674.0,682.0,NaN,43.0,51.0,690.0,698.0
14,6,3,takes,65,70,712,717,1,27.0,35.0,674.0,682.0,NaN,71.0,91.0,718.0,738.0
15,7,0,borrows,9,16,754,761,1,0.0,8.0,745.0,753.0,24,17.0,43.0,762.0,788.0
16,7,1,weigh,47,52,792,797,1,0.0,8.0,745.0,753.0,NaN,53.0,82.0,798.0,827.0
17,8,0,puts,24,28,853,857,24,20.0,23.0,849.0,852.0,NaN,29.0,42.0,858.0,871.0
18,8,1,find,60,64,889,893,NaN,NaN,NaN,NaN,NaN,1,69.0,95.0,898.0,924.0
19,8,3,using,81,86,910,915,1,74.0,77.0,903.0,906.0,NaN,87.0,91.0,916.0,920.0
20,8,4,is,104,106,933,935,24,100.0,103.0,929.0,932.0,25,107.0,190.0,936.0,1019.0
21,8,5,know,118,122,947,951,24,100.0,103.0,929.0,932.0,25,123.0,190.0,952.0,1019.0
22,8,6,needs,174,179,1003,1008,25,142.0,173.0,971.0,1002.0,NaN,180.0,190.0,1009.0,1019.0
23,8,7,measure,183,190,1012,1019,25,123.0,141.0,952.0,970.0,NaN,NaN,NaN,NaN,NaN
24,9,0,finds,18,23,1039,1044,24,14.0,17.0,1035.0,1038.0,NaN,24.0,58.0,1045.0,1079.0
25,9,1,tells,63,68,1084,1089,24,14.0,17.0,1035.0,1038.0,"27,2,26",69.0,124.0,1090.0,1145.0
26,10,1,forced,45,51,1192,1198,"1,28",0.0,41.0,1147.0,1188.0,NaN,52.0,84.0,1199.0,1231.0
27,10,2,reveal,55,61,1202,1208,1,33.0,41.0,1180.0,1188.0,NaN,62.0,84.0,1209.0,1231.0
28,11,0,goes,7,11,1240,1244,2,0.0,6.0,1233.0,1239.0,NaN,12.0,23.0,1245.0,1256.0
29,11,1,enters,28,34,1261,1267,2,0.0,6.0,1233.0,1239.0,NaN,35.0,55.0,1268.0,1288.0

In [20]:
import pandas as pd
technologies = {
    'Courses':["Spark","PySpark","Hadoop","Python","pandas"],
    'Fee' :[20000,25000,26000,22000,24000],
    'Duration':['30day','40days','35days','40days','60days'],
    'Discount':[1000,2300,1200,2500,2000]
              }
index_labels=['r1','r2','r3','r4','r5']
df = pd.DataFrame(technologies,index=index_labels)
print(df)

    Courses    Fee Duration  Discount
r1    Spark  20000    30day      1000
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1200
r4   Python  22000   40days      2500
r5   pandas  24000   60days      2000

In [21]:
df2=df.loc[(df['Discount'] >= 20000) | (df['Fee'] >= 23000 )]
print(df2)

    Courses    Fee Duration  Discount
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1200
r5   pandas  24000   60days      2000

In [13]:
import pandas as pd
super_df = pd.read_csv('ali-baba-and-forty-thieves.supersense', sep=',')
super_df.iloc[:30]

,start_token,end_token,supersense_category,text,StartByte,EndByte
0,1,1,noun.communication,story,4,9
1,2,3,verb.change,takes place,10,21
2,5,5,noun.location,Baghdad,25,32
3,9,9,noun.time,era,52,55
4,11,12,noun.person,Ali Baba,57,65
5,16,16,noun.person,brother,80,87
6,17,17,noun.person,Cassim,88,94
7,18,18,verb.stative,are,95,98
8,20,20,noun.person,sons,103,107
9,23,23,noun.person,merchant,113,121
10,27,27,noun.event,death,133,138
11,30,30,noun.person,father,148,154
12,34,34,noun.person,Cassim,167,173
13,35,35,verb.social,marries,174,181
14,38,38,noun.person,woman,192,197
15,40,40,verb.change,becomes,202,209
16,47,47,verb.consumption,building,222,230
17,50,50,noun.person,father,240,246
18,52,52,noun.act,business,249,257
19,55,56,noun.person,Ali Baba,264,272
20,57,57,verb.social,marries,273,280
21,60,60,noun.person,woman,288,293
22,62,63,verb.social,settles into,298,310
23,65,65,noun.act,trade,315,320
24,68,68,noun.person,woodcutter,326,336
25,71,71,noun.time,day,342,345
26,72,73,noun.person,Ali Baba,346,354
27,74,74,verb.stative,is,355,357
28,77,77,verb.contact,collecting,366,376
29,79,79,verb.contact,cutting,381,388

In [5]:
event_coref.loc[(event_coref['sentence_id'] == 10) & (event_coref['verb_id'] == 1)]

,sentence_id,verb_id,verb,verb_start_byte,verb_end_byte,verb_start_byte_text,verb_end_byte_text,subj_coref_ids,subj_start_byte,subj_end_byte,subj_start_byte_text,subj_end_byte_text,dobj_coref_ids,dobj_start_byte,dobj_end_byte,dobj_start_byte_text,dobj_end_byte_text
26,10,1,forced,45,51,1192,1198,"1,28",0.0,41.0,1147.0,1188.0,NaN,52.0,84.0,1199.0,1231.0

In [9]:
event_coref.iloc[:30]

,sentence_id,verb_id,verb,verb_start_byte,verb_end_byte,verb_start_byte_text,verb_end_byte_text,subj_coref_ids,subj_start_byte,subj_end_byte,subj_start_byte_text,subj_end_byte_text,dobj_coref_ids,dobj_start_byte,dobj_end_byte,dobj_start_byte_text,dobj_end_byte_text
0,1,0,are,38,41,95,98,"1,7,2",0.0,37.0,57.0,94.0,8,42.0,64.0,99.0,121.0
1,2,0,marries,51,58,174,181,2,33.0,50.0,156.0,173.0,11,59.0,74.0,182.0,197.0
2,2,1,becomes,79,86,202,209,2,33.0,50.0,156.0,173.0,NaN,87.0,97.0,210.0,220.0
3,2,2,building,99,107,222,230,2,33.0,50.0,156.0,173.0,10,108.0,134.0,231.0,257.0
4,2,3,marries,150,157,273,280,1,141.0,149.0,264.0,272.0,13,158.0,170.0,281.0,293.0
5,2,4,settles,175,182,298,305,1,141.0,149.0,264.0,272.0,NaN,NaN,NaN,NaN,NaN
6,3,0,is,17,19,355,357,1,0.0,16.0,338.0,354.0,NaN,20.0,73.0,358.0,411.0
7,3,1,collecting,28,38,366,376,1,8.0,16.0,346.0,354.0,NaN,51.0,59.0,389.0,397.0
8,3,3,happens,82,89,420,427,NaN,NaN,NaN,NaN,NaN,16,90.0,156.0,428.0,494.0
9,3,4,overhear,93,101,431,439,1,79.0,81.0,417.0,419.0,16,102.0,156.0,440.0,494.0
10,5,0,opens,3,8,565,570,NaN,0.0,2.0,562.0,564.0,3,9.0,83.0,571.0,645.0
11,5,1,seals,42,47,604,609,NaN,0.0,2.0,562.0,564.0,3,48.0,54.0,610.0,616.0
12,6,1,gone,21,25,668,672,20,5.0,16.0,652.0,663.0,NaN,NaN,NaN,NaN,NaN
13,6,2,enters,36,42,683,689,1,27.0,35.0,674.0,682.0,NaN,43.0,51.0,690.0,698.0
14,6,3,takes,65,70,712,717,1,27.0,35.0,674.0,682.0,NaN,71.0,91.0,718.0,738.0
15,7,0,borrows,9,16,754,761,1,0.0,8.0,745.0,753.0,24,17.0,43.0,762.0,788.0
16,7,1,weigh,47,52,792,797,1,0.0,8.0,745.0,753.0,NaN,53.0,82.0,798.0,827.0
17,8,0,puts,24,28,853,857,24,20.0,23.0,849.0,852.0,NaN,29.0,42.0,858.0,871.0
18,8,1,find,60,64,889,893,NaN,NaN,NaN,NaN,NaN,1,69.0,95.0,898.0,924.0
19,8,3,using,81,86,910,915,1,74.0,77.0,903.0,906.0,NaN,87.0,91.0,916.0,920.0
20,8,4,is,104,106,933,935,24,100.0,103.0,929.0,932.0,25,107.0,190.0,936.0,1019.0
21,8,5,know,118,122,947,951,24,100.0,103.0,929.0,932.0,25,123.0,190.0,952.0,1019.0
22,8,6,needs,174,179,1003,1008,25,142.0,173.0,971.0,1002.0,NaN,180.0,190.0,1009.0,1019.0
23,8,7,measure,183,190,1012,1019,25,123.0,141.0,952.0,970.0,NaN,NaN,NaN,NaN,NaN
24,9,0,finds,18,23,1039,1044,24,14.0,17.0,1035.0,1038.0,NaN,24.0,58.0,1045.0,1079.0
25,9,1,tells,63,68,1084,1089,24,14.0,17.0,1035.0,1038.0,"27,2,26",69.0,124.0,1090.0,1145.0
26,10,1,forced,45,51,1192,1198,"1,28",0.0,41.0,1147.0,1188.0,NaN,52.0,84.0,1199.0,1231.0
27,10,2,reveal,55,61,1202,1208,1,33.0,41.0,1180.0,1188.0,NaN,62.0,84.0,1209.0,1231.0
28,11,0,goes,7,11,1240,1244,2,0.0,6.0,1233.0,1239.0,NaN,12.0,23.0,1245.0,1256.0
29,11,1,enters,28,34,1261,1267,2,0.0,6.0,1233.0,1239.0,NaN,35.0,55.0,1268.0,1288.0

In [11]:
srl=pd.read_json("ali-baba-and-forty-thieves/ali-baba-and-forty-thieves.srl.json")
srl

,verbs,words
0,"[{'verb': 'takes', 'description': '[ARG1: The ...","[The, story, takes, place, in, Baghdad, during..."
1,"[{'verb': 'are', 'description': '[ARG1: Ali Ba...","[Ali, Baba, and, his, elder, brother, Cassim, ..."
2,"[{'verb': 'marries', 'description': '[ARGM-TMP...","[After, the, death, of, their, father, ,, the,..."
3,"[{'verb': 'is', 'description': '[ARG1: One day...","[One, day, Ali, Baba, is, at, work, collecting..."
4,"[{'verb': 'is', 'description': '[ARG1: The tre...","[The, treasure, is, in, a, cave, ,, the, mouth..."
5,"[{'verb': 'opens', 'description': '[ARG2: It] ...","[It, opens, on, the, words, "", Open, ,, Simsim..."
6,"[{'verb': 'are', 'description': 'When the thie...","[When, the, thieves, are, gone, ,, Ali, Baba, ..."
7,"[{'verb': 'borrows', 'description': '[ARG0: Al...","[Ali, Baba, borrows, his, sister, -, in, -, la..."
8,"[{'verb': 'puts', 'description': '[R-ARG0: Unb...","[Unbeknownst, to, Ali, ,, she, puts, a, blob, ..."
9,"[{'verb': 'finds', 'description': '[R-ARG0: To...","[To, her, shock, ,, she, finds, a, gold, coin,..."
10,"[{'verb': 'is', 'description': 'Under pressure...","[Under, pressure, from, his, brother, ,, Ali, ..."
11,"[{'verb': 'goes', 'description': '[ARG1: Cassi...","[Cassim, goes, to, the, cave, and, enters, wit..."
12,"[{'verb': 'find', 'description': '[ARG0: The t...","[The, thieves, find, him, there, ,, and, kill,..."
13,"[{'verb': 'does', 'description': 'When his bro...","[When, his, brother, does, not, come, back, ,,..."
14,"[{'verb': 'brings', 'description': '[ARG0: Ali...","[Ali, Baba, brings, the, body, home, ,, where,..."
15,"[{'verb': 'purchases', 'description': '[ARGM-D...","[First, ,, Morgiana, purchases, medicines, fro..."
16,"[{'verb': 'stitches', 'description': '[ARGM-LO...","[There, ,, overnight, ,, the, tailor, stitches..."
17,"[{'verb': 'are', 'description': '[ARG1: Ali an...","[Ali, and, his, family, are, able, to, give, C..."
18,"[{'verb': 'finding', 'description': '[ARG0: Th...","[The, thieves, ,, finding, the, body, gone, ,,..."
19,"[{'verb': 'goes', 'description': '[ARG1: One o...","[One, of, the, thieves, goes, down, to, the, t..."
20,"[{'verb': 'Realizing', 'description': '[V: Rea...","[Realizing, that, the, dead, man, must, have, ..."
21,"[{'verb': 'is', 'description': 'The tailor [V:...","[The, tailor, is, blindfolded, again, ,, and, ..."
22,"[{'verb': 'marks', 'description': '[ARG0: The ...","[The, thief, marks, the, door, with, a, symbol..."
23,"[{'verb': 'is', 'description': '[ARG1: The pla...","[The, plan, is, for, the, other, thieves, to, ..."
24,"[{'verb': 'has', 'description': 'However , the...","[However, ,, the, thief, has, been, seen, by, ..."
25,"[{'verb': 'return', 'description': '[ARGM-TMP:...","[When, the, 40, thieves, return, that, night, ..."
26,"[{'verb': 'tries', 'description': '[ARGM-TMP: ...","[The, next, day, ,, another, thief, revisits, ..."
27,"[{'verb': 'foils', 'description': '[ARGM-MNR: ...","[Again, Morgiana, foils, the, plan, by, making..."
28,"[{'verb': 'is', 'description': 'The second thi...","[The, second, thief, is, killed, for, his, stu..."
29,"[{'verb': 'goes', 'description': '[ARGM-TMP: A...","[At, last, ,, the, head, thief, goes, and, loo..."
30,"[{'verb': 'memorizes', 'description': '[ARGM-T...","[This, time, ,, he, memorizes, every, detail, ..."
31,"[{'verb': 'pretends', 'description': '[ARG0: T...","[The, chief, of, the, thieves, pretends, to, b..."
32,"[{'verb': 'is', 'description': 'Once [ARG1: Al...","[Once, Ali, Baba, is, asleep, ,, the, thieves,..."
33,"[{'verb': 'discovers', 'description': '[ARGM-T...","[Again, ,, Morgiana, discovers, and, foils, th..."
34,"[{'verb': 'comes', 'description': '[ARGM-TMP: ...","[When, their, leader, comes, to, rouse, his, m..."
35,"[{'verb': 'exact', 'description': 'To [V: exac...","[To, exact, revenge, ,, after, some, time, the..."
36,"[{'verb': 'is', 'description': 'The thief [V: ...","[The, thief, is, recognized, by, Morgiana, ,, ..."
37,"[{'verb': 'is', 'description': '[ARG1: Ali Bab...","[Ali, Baba, is, at, first, angry, with, Morgia..."
38,"[{'verb': 'is', 'description': 'Ali Baba [V: i...","[Ali, Baba, is, then, left, as, the, only, one..."
39,"[{'verb': 'ends', 'description': '[ARGM-DIS: T...","[Thus, ,, the, story, ends, happily, for, ever..."

In [22]:
event_coref.iloc[0]['verb_start_byte']-1

37